name : egzact
cmdname : egzact
summary : Strengthen weak points of the shell
description : New command line tools with three concepts.
version : 2.0.0
changelog : Support Egison 4.0.0
url : https://github.com/greymd/egzact
author : Yasuhiro, Yamada
email : yamadagrep@gmail.com
libdir : /usr/lib
