name : egzact
cmdname : egzact
summary : Strengthen weak points of the shell
description : New command line tools with three concepts.
version : 1.3.1
changelog : bug fix.
url : https://github.com/greymd/egzact
author : Yasuhiro, Yamada
email : greengregson@gmail.com
libdir : /usr/lib
